export const lessons = [
  {
    id: 1,
    title: "How to Learn Guitar",
    description: "How to learn guitar.",
    sections: [
      {
        type: "h3",
        style: "",
        content: "What is your goal?",
      },
      {
        type: "p",
        style: "",
        content:
          "What you need to learn depends on what you want to do, and what kind of music you want to play. I am going to focus on skills that are useful for all types of guitar players and essential for most.",
      },
      {
        type: "h3",
        style: "",
        content: "What I'm going to cover",
      },
      {
        type: "h3",
        style: "",
        content: "The Basics",
      },
      {
        type: "p",
        style: "",
        content:
          "Mention the absolute basics, how to hold it learn the parts, ect",
      },
      {
        type: "h3",
        style: "",
        content: "Guitar Specific Technique",
      },
      {
        type: "p",
        style: "",
        content: "Open Chords and basic strumming.",
      },
      {
        type: "p",
        style: "",
        content: "Barre Chords and the caged system.",
      },
      {
        type: "p",
        style: "",
        content:
          "The Pentatonic Scale and basic lead playing skills, phrasing, tone, ect.",
      },
      {
        type: "p",
        style: "",
        content:
          "Advanced lead playing including arpeggios the major scale, chromaticism, right hand technique.",
      },
      {
        type: "p",
        style: "",
        content:
          "Advanced rhythm playing including right hand technique, extended chords, voiceings, inversions, and more.",
      },
      {
        type: "h3",
        style: "",
        content: "Learning Songs",
      },
      {
        type: "p",
        style: "",
        content: "Youtube, By ear, Tabs, Chord charts, Standard notation",
      },
      {
        type: "h3",
        style: "",
        content: "Essential Music Theory",
      },
      {
        type: "p",
        style: "",
        content: "time signatures, rythym and counting",
      },
      {
        type: "p",
        style: "",
        content: "the major scale making chords, and keys",
      },
      {
        type: "h3",
        style: "",
        content: "Musicianship",
      },
      {
        type: "p",
        style: "",
        content: "timing and feel",
      },
      {
        type: "p",
        style: "",
        content: "ear training",
      },
      {
        type: "p",
        style: "",
        content: "playing with others.",
      },
      {
        type: "p",
        style: "",
        content:
          "layout sections: Guitar specific technique, learning songs, music theory, ear training, feel, improvising, make sure to mention playing with others.",
      },
    ],
  },
  {
    id: 2,
    title: "Essential Music Theory",
    description: "Notes In Music Major Scale How to Make Chords Keys",
    sections: [
      { type: "h3", style: "", content: "Notes In Music" },
      { type: "p", style: "", content: "Notes In Music" },
      { type: "h3", style: "", content: "Major Scale" },
      { type: "p", style: "", content: "Major Scale" },
      { type: "h3", style: "", content: "Invtervals and How to Make Chords" },
      { type: "p", style: "", content: "Invtervals and How to Make Chords" },
      { type: "h3", style: "", content: "Keys" },
      { type: "p", style: "", content: "Keys" },
      { type: "h3", style: "", content: "Minor Scale" },
      { type: "p", content: "Minor Scale and minor keys" },
    ],
  },
  {
    id: 3,
    title: "Thoughts on Ear Training",
    description: "Thoughts on ear training",
    sections: [
      { type: "h3", style: "", content: "Why ear training" },
      {
        type: "p",
        style: "",
        content:
          "Learning songs that have't been written down and dont have videos.",
      },
      {
        type: "p",
        style: "",
        content: "Learning songs on the fly while playing with others.",
      },
      {
        type: "p",
        style: "",
        content: "Being able to play whats in your head.",
      },
      {
        type: "p",
        style: "",
        content:
          "Being able to remember things you hear and remember things longer.",
      },
      {
        type: "h3",
        style: "",
        content: "super quick note about the traditiional interval method",
      },
      {
        type: "p",
        style: "",
        content:
          "Traditional methods of ear training teach you to recongnize one interval at a time. (Being able to know what one note is if you know what the previous note was.) Then they work on recognizing chords.super quick note about the traditiional interval method",
      },
      {
        type: "h3",
        style: "",
        content:
          "why I built my ear training system,easy acoustic songs and melodies vs full tracks",
      },
      {
        type: "p",
        style: "",
        content:
          "why I built my ear training system,easy acoustic songs and melodies vs full tracks. I would rather spend my time learning songs and melodies than just intervals.",
      },
      {
        type: "h3",
        style: "",
        content: "using the pentatonic scale to find the key of a song",
      },
      {
        type: "p",
        style: "",
        content: "using the pentatonic scale to find the key of a song",
      },
      {
        type: "h3",
        style: "",
        content: "not talking about how ear training effects",
      },
      {
        type: "p",
        style: "",
        content: "tone, hearing theory, developing timing",
      },
    ],
  },
  {
    id: 4,
    title: "Applying Theory to the Fretboard",
    description: "Applying Theory to the Fretboard",
    sections: [
      {
        type: "h3",
        style: "",
        content:
          "Prerequisites Learning the Fretboard, learn the E and A String, Fretboard Octive Hack,",
      },
      {
        type: "p",
        style: "",
        content:
          "Prerequisites Learning the Fretboard, learn the E and A String, Fretboard Octive Hack,",
      },
      { type: "h3", style: "", content: "Barre Chords and the Caged System," },
      { type: "p", style: "", content: "Barre Chords and the Caged System" },
      { type: "h3", style: "", content: "Right Hand Technique" },
      {
        type: "p",
        style: "",
        content: "Advanced strumming, muting, travis picking,",
      },
      { type: "h3", style: "", content: "The Pentatonic Scale," },
      { type: "p", style: "", content: "The Pentatonic Scale," },
      { type: "h3", style: "", content: "Triads" },
      { type: "p", style: "", content: "Triads" },
      { type: "h3", style: "", content: "Playing the Changes" },
      { type: "p", style: "", content: "Playing the Changes" },
      { type: "h3", style: "", content: "Arpeggios" },
      { type: "p", style: "", content: "Arpeggios" },
      { type: "h3", style: "", content: "OP Exersice my favorite exersize" },
      { type: "p", style: "", content: "OP Exersice my favorite exersize" },
    ],
  },
  {
    id: 5,
    title: "Playing With Others",
    description: "Playing With Others",
    sections: [
      { type: "h3", style: "", content: "Improvising" },
      { type: "p", style: "", content: "improvising" },
      { type: "h3", style: "", content: "Feel and Ears. Musicianship" },
      { type: "p", style: "", content: "feel and ears. Musicianship" },
      { type: "h3", style: "", content: "Nashville Number System" },
      { type: "p", style: "", content: "standard tunes" },
      { type: "p", style: "", content: "Gear and Tone" },
    ],
  },
  {
    id: 6,
    title: "Learning Songs",
    description: "Learning Songs",
    sections: [
      { type: "h3", style: "", content: "The Different Ways to Learn Songs" },
      {
        type: "p",
        style: "",
        content:
          "Videos, By ear, tabs, chord tabs, chord charts, standard notation,",
      },
      { type: "h3", style: "", content: "Youtube" },
      { type: "p", style: "", content: "Youtube" },
      { type: "h3", style: "", content: "Learning Songs By Ear" },
      { type: "p", style: "", content: "Learning songs by ear" },
      { type: "h3", style: "", content: "Tab" },
      { type: "p", style: "", content: "Tabs" },
      { type: "h3", style: "", content: "Chord Charts" },
      { type: "p", style: "", content: "Chord charts" },
      { type: "h3", style: "", content: "Standard Notation" },
      { type: "p", style: "", content: "Standard notation" },
    ],
  },
  {
    id: 7,
    title: "The Blues",
    description: "The Blues",
    sections: [
      { type: "h3", style: "", content: "The Blues" },
      { type: "p", style: "", content: "the blues" },
    ],
  },
  {
    id: 8,
    title: "My Favorite Online Resources and Teachers",
    description: "My Favorite Online Resources and Teachers",
    sections: [
      {
        type: "h3",
        style: "",
        content: "My Favorite Online Resources and Teachers",
      },
      { type: "p", style: "", content: "Marty Music" },
      { type: "p", style: "", content: "Michael Palmisano" },
      { type: "p", style: "", content: "Eric Haughen" },
      { type: "p", style: "", content: "Desi Serna" },
      { type: "p", style: "", content: "Ultimate Guitar" },
      { type: "p", style: "", content: "UK Guitar Chords" },
      { type: "p", style: "", content: "Chord Sheets" },
      {
        type: "h3",
        style: "",
        content: "Other Mentions",
      },
    ],
  },
];

export const instrumentDifficulties = {
  guitar: [
    "intervals-g",
    "intervals",
    "one-string-melody",
    "melody",
    "easy-riffs",
    "hard-riffs",
    "key-of-g-diatonic-chords-easy",
    "key-of-g-diatonic-chords-hard",
    "key-of-g-diatonic-chords-with-extensions",
    "any-key-diatonic-chords-easy",
    "any-key-diatonic-chords-hard",
    "any-key-diatonic-chords-with-extensions",
    "no-restrictions",
  ],
  piano: [
    "intervals",
    "easy-melodies-or-basslines",
    "hard-melodies-or-basslines",
    "key-of-c-diatonic-chords-easy",
    "key-of-c-diatonic-chords-hard",
    "key-of-c-diatonic-chords-with-extensions",
    "key-of-c-diatonic-chords-easy-two-hands",
    "key-of-c-diatonic-chords-hard-two-hands",
    "key-of-c-diatonic-chords-with-extensions-two-hands",
    "any-key-diatonic-chords-easy",
    "any-key-diatonic-chords-hard",
    "any-key-diatonic-chords-with-extensions",
    "no-restrictions",
  ],
  bass: [
    "intervals",
    "one-string-only",
    "licks-and-melodies-easy",
    "key-of-g-riffs-and-chord-progressions-easy",
    "key-of-g-riffs-and-chord-progressions-hard",
    "any-key-riffs-and-chord-progressions-easy",
    "no-restrictions",
  ],
  "guitar-bass": [
    "key-of-g-diatonic-chords-easy",
    "key-of-g-diatonic-chords-hard",
    "any-key-diatonic-chords-easy",
    "any-key-diatonic-chords-hard",
    "no-restrictions",
  ],
  "guitar-bass-piano": [
    "key-of-g-diatonic-chords-easy",
    "key-of-g-diatonic-chords-hard",
    "any-key-diatonic-chords-easy",
    "any-key-diatonic-chords-hard",
    "no-restrictions",
  ],
};

export const realSongListRealDifficultyFlatArray = [
  {
    audioTrackId: 1001,
    userId: 1,
    songName: "El Paso",
    songTip: "el paso tip",
    songKey: "",
    songChords: "el paso chords",
    songInstrument: "guitar",
    songDifficulty: "melody",
    songBlobUrl: "/Songs/ET_MO_A_ElPaso.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1002,
    userId: 1,
    songName: "GOTTV1",
    songTip: "gotv1 tip",
    songKey: "",
    songChords: "gotv1 chords",
    songInstrument: "guitar",
    songDifficulty: "melody",
    songBlobUrl: "/Songs/ET_MO_I_GOTTV1.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1003,
    userId: 1,
    songName: "1415G",
    songTip: "Come on dude really?",
    songKey: "G",
    songChords: "1415G chords",
    songInstrument: "guitar",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_1415G.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1004,
    userId: 1,
    songName: "1465G",
    songTip: "Come on dude really?",
    songKey: "G",
    songChords: "1465G chords",
    songInstrument: "guitar",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_1465G.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1005,
    userId: 1,
    songName: "1524G",
    songTip: "Come on dude really?",
    songKey: "G",
    songChords: "1524G chords",
    songInstrument: "guitar",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_1524G.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1006,
    userId: 1,
    songName: "1645G",
    songTip: "Come on dude really?",
    songKey: "G",
    songChords: "1645G chords",
    songInstrument: "guitar",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_1645G.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1007,
    userId: 1,
    songName: "5411G",
    songTip: "Come on dude really?",
    songKey: "G",
    songChords: "5411G chords",
    songInstrument: "guitar",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_5411G.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1008,
    userId: 1,
    songName: "Blue Chorus",
    songTip: "Blue Chorus tip",
    songKey: "",
    songChords: "Blue Chorus chords",
    songInstrument: "guitar",
    songDifficulty: "any-key-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_Blue_Chorus.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1009,
    userId: 1,
    songName: "Simple Man",
    songTip: "Simple Man tip",
    songKey: "",
    songChords: "Simple Man chords",
    songInstrument: "guitar",
    songDifficulty: "any-key-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_Simple_Man.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1010,
    userId: 1,
    songName: "Hurt",
    songTip: "Hurt tip",
    songKey: "",
    songChords: "Hurt chords",
    songInstrument: "guitar",
    songDifficulty: "any-key-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_Hurt.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1011,
    userId: 1,
    songName: "Cavalry",
    songTip: "Cavalry tip",
    songKey: "",
    songChords: "Cavalry chords",
    songInstrument: "guitar",
    songDifficulty: "no-restrictions",
    songBlobUrl: "/Songs/ET_Guitar_Cavalry.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1012,
    userId: 1,
    songName: "Nobody Knows You When You're Down And Out",
    songTip: "Nobody Knows You When You're Down And Out tip",
    songKey: "",
    songChords: "Nobody Knows You When You're Down And Out chords",
    songInstrument: "guitar",
    songDifficulty: "no-restrictions",
    songBlobUrl:
      "/Songs/ET_Guitar_Nobody_Knows_You_When_You're_Down_And_Out.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1013,
    userId: 1,
    songName: "Something",
    songTip: "Something tip",
    songKey: "",
    songChords: "Something chords",
    songInstrument: "guitar",
    songDifficulty: "no-restrictions",
    songBlobUrl: "/Songs/ET_Guitar_Something.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1014,
    userId: 1,
    songName: "G 15",
    songTip: "G 15 tip",
    songKey: "G",
    songChords: "G 15 chords  ",
    songInstrument: "bass",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_BO_B_G_15.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1015,
    userId: 1,
    songName: "G 1415",
    songTip: "G 1415 tip",
    songKey: "G",
    songChords: "G 1415 chords",
    songInstrument: "bass",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_BO_B_G_1415.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1016,
    userId: 1,
    songName: "A 1415",
    songTip: "A 1415 tip",
    songKey: "A",
    songChords: "A 1415 chords",
    songInstrument: "bass",
    songDifficulty: "any-key-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_BO_I_A_1415.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1017,
    userId: 1,
    songName: "12BB",
    songTip: "12BB tip",
    songKey: "",
    songChords: "12BB chords",
    songInstrument: "bass",
    songDifficulty: "any-key-diatonic-chords-hard",
    songBlobUrl: "/Songs/ET_BO_A_12BB.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1024,
    userId: 1,
    songName: "Second",
    songTip: "",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "intervals-g",
    songBlobUrl: "/Songs/Second.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1025,
    userId: 1,
    songName: "Minor Third",
    songTip: "",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "intervals-g",
    songBlobUrl: "/Songs/MinorThird.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1026,
    userId: 1,
    songName: "Major Third",
    songTip: "",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "intervals-g",
    songBlobUrl: "/Songs/MajorThird.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1027,
    userId: 1,
    songName: "Fourth",
    songTip: "",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "intervals-g",
    songBlobUrl: "/Songs/Fourth.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1018,
    userId: 1,
    songName: "Fifth",
    songTip: "G",
    songKey: "",
    songChords: "1-5 G-D",
    songInstrument: "guitar",
    songDifficulty: "intervals-g",
    songBlobUrl: "/Songs/1-5GI.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1019,
    userId: 1,
    songName: "Sixth",
    songTip: "G",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "intervals-g",
    songBlobUrl: "/Songs/Sixth.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1020,
    userId: 1,
    songName: "Seventh",
    songTip: "G",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "intervals-g",
    songBlobUrl: "/Songs/Seventh.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1021,
    userId: 1,
    songName: "Major Seventh",
    songTip: "G",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "intervals-g",
    songBlobUrl: "/Songs/MajorSeventh.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1022,
    userId: 1,
    songName: "Octave",
    songTip: "G",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "intervals-g",
    songBlobUrl: "/Songs/Octave.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1019,
    userId: 1,
    songName: "Here Comes The Sun Chorus",
    songTip: "",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "melody",
    songBlobUrl: "Songs/HereComesTheSunChorusMelodyOnAcoustic.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1020,
    userId: 1,
    songName: "Here Comes The Sun Chorus Lick",
    songTip: "",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "melody",
    songBlobUrl: "Songs/HereComesTheSunEndOfChorusDLick.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1021,
    userId: 1,
    songName: "TheLongAndWindingRoadVerseMelodyGuitar",
    songTip: "",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "melody",
    songBlobUrl: "Songs/TheLongAndWindingRoadVerseMelodyGuitar.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1022,
    userId: 1,
    songName: "My Girl",
    songTip: "",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "easy-riffs",
    songBlobUrl: "/Songs/MyGirlLeadRiff.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 1023,
    userId: 1,
    songName: "Day Tripper",
    songTip: "",
    songKey: "",
    songChords: "",
    songInstrument: "guitar",
    songDifficulty: "easy-riffs",
    songBlobUrl: "/Songs/DayTripperRiff.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
];

export const notes = [
  { display: "A", value: "A" },
  { display: "A#/Bb", value: "A#" },
  { display: "B", value: "B" },
  { display: "C", value: "C" },
  { display: "C#/Db", value: "C#" },
  { display: "D", value: "D" },
  { display: "D#/Eb", value: "D#" },
  { display: "E", value: "E" },
  { display: "F", value: "F" },
  { display: "F#/Gb", value: "F#" },
  { display: "G", value: "G" },
  { display: "G#/Ab", value: "G#" },
];

export const scales = {
  note: [0], // Just the root note
  major: [0, 2, 4, 5, 7, 9, 11],
  minor: [0, 2, 3, 5, 7, 8, 10],
  majorPentatonic: [0, 2, 4, 7, 9],
  minorPentatonic: [0, 3, 5, 7, 10],
  majorArpeggio: [0, 4, 7],
  minorArpeggio: [0, 3, 7],
};
export const notesss = [
  "A",
  "A#",
  "B",
  "C",
  "C#",
  "D",
  "D#",
  "E",
  "F",
  "F#",
  "G",
  "G#",
];

export const stringNames = ["E", "B", "G", "D", "A", "E"];
