export const lessons = [
  {
    id: 1,
    title: "How to Learn Guitar",
    description: "How to learn guitar.",
    sections: [
      {
        type: "h3",
        style: "",
        content: "What is your goal?",
      },
      {
        type: "p",
        style: "",
        content:
          "kind of guitar, type of music, ect. explain that I am going to cover the stuff that applies to pretty much everyone and helps you to be well rounded",
      },
      {
        type: "h3",
        style: "",
        content: "What I'm going to cover",
      },
      {
        type: "p",
        style: "",
        content:
          "I am going to cover the stuff that applies to pretty much everyone and helps you to be well rounded",
      },
      {
        type: "p",
        style: "",
        content:
          "Mention the absolute basics, how to hold it learn the parts, ect",
      },
      {
        type: "p",
        style: "",
        content:
          "layout sections: Guitar specific technique, learning songs, music theory, ear training, feel, improvising, make sure to mention playing with others.",
      },
    ],
  },
  {
    id: 2,
    title: "Essential Music Theory",
    description: "Notes In Music Major Scale How to Make Chords Keys",
    sections: [
      { type: "h3", style: "", content: "Notes In Music" },
      { type: "p", style: "", content: "Notes In Music" },
      { type: "h3", style: "", content: "Major Scale" },
      { type: "p", style: "", content: "Major Scale" },
      { type: "h3", style: "", content: "Minor Scale" },
      { type: "p", content: "Minor Scale" },
      { type: "h3", style: "", content: "Invtervals and How to Make Chords" },
      { type: "p", style: "", content: "Invtervals and How to Make Chords" },
      { type: "h3", style: "", content: "Keys" },
      { type: "p", style: "", content: "Keys" },
    ],
  },
  {
    id: 3,
    title: "Thoughts on Ear Training",
    description: "Thoughts on ear training",
    sections: [
      { type: "h3", style: "", content: "Why ear training" },
      { type: "p", style: "", content: "Why ear training" },
      {
        type: "h3",
        style: "",
        content: "super quick note about the traditiional interval method",
      },
      {
        type: "p",
        style: "",
        content: "super quick note about the traditiional interval method",
      },
      {
        type: "h3",
        style: "",
        content:
          "why I built my ear training system,easy acoustic songs and melodies vs full tracks",
      },
      {
        type: "p",
        style: "",
        content:
          "why I built my ear training system,easy acoustic songs and melodies vs full tracks",
      },
      {
        type: "h3",
        style: "",
        content: "using the pentatonic scale to find the key of a song",
      },
      {
        type: "p",
        style: "",
        content: "using the pentatonic scale to find the key of a song",
      },
    ],
  },
  {
    id: 4,
    title: "Applying Theory to the Fretboard",
    description: "Applying Theory to the Fretboard",
    sections: [
      {
        type: "h3",
        style: "",
        content:
          "Prerequisites Learning the Fretboard, learn the E and A String, Fretboard Octive Hack,",
      },
      {
        type: "p",
        style: "",
        content:
          "Prerequisites Learning the Fretboard, learn the E and A String, Fretboard Octive Hack,",
      },
      { type: "h3", style: "", content: "Barre Chords and the Caged System," },
      { type: "p", style: "", content: "Barre Chords and the Caged System," },
      { type: "h3", style: "", content: "The Pentatonic Scale," },
      { type: "p", style: "", content: "The Pentatonic Scale," },
      { type: "h3", style: "", content: "Triads" },
      { type: "p", style: "", content: "Triads" },
      { type: "h3", style: "", content: "Playing the Changes" },
      { type: "p", style: "", content: "Playing the Changes" },
      { type: "h3", style: "", content: "Arpeggios" },
      { type: "p", style: "", content: "Arpeggios" },
      { type: "h3", style: "", content: "OP Exersice my favorite exersize" },
      { type: "p", style: "", content: "OP Exersice my favorite exersize" },
    ],
  },
  {
    id: 5,
    title: "Playing With Others",
    description: "Playing With Others",
    sections: [
      { type: "h3", style: "", content: "Improvising" },
      { type: "p", style: "", content: "improvising" },
      { type: "h3", style: "", content: "Feel and Ears. Musicianship" },
      { type: "p", style: "", content: "feel and ears. Musicianship" },
      { type: "h3", style: "", content: "Nashville Number System" },
      { type: "p", style: "", content: "standard tunes" },
    ],
  },
  {
    id: 6,
    title: "Learning Songs",
    description: "Learning Songs",
    sections: [
      { type: "h3", style: "", content: "The Different Ways to Learn Songs" },
      {
        type: "p",
        style: "",
        content:
          "Videos, By ear, tabs, chord tabs, chord charts, standard notation,",
      },
      { type: "h3", style: "", content: "Youtube" },
      { type: "p", style: "", content: "Youtube" },
      { type: "h3", style: "", content: "Learning Songs By Ear" },
      { type: "p", style: "", content: "Learning songs by ear" },
      { type: "h3", style: "", content: "Tab" },
      { type: "p", style: "", content: "Tabs" },
      { type: "h3", style: "", content: "Chord Charts" },
      { type: "p", style: "", content: "Chord charts" },
      { type: "h3", style: "", content: "Standard Notation" },
      { type: "p", style: "", content: "Standard notation" },
    ],
  },
  {
    id: 7,
    title: "The Blues",
    description: "The Blues",
    sections: [
      { type: "h3", style: "", content: "The Blues" },
      { type: "p", style: "", content: "the blues" },
    ],
  },
  {
    id: 8,
    title: "My Favorite Online Resources and Teachers",
    description: "My Favorite Online Resources and Teachers",
    sections: [
      {
        type: "h3",
        style: "",
        content: "My Favorite Online Resources and Teachers",
      },
      { type: "p", style: "", content: "the importance of the blues" },
    ],
  },
];

export const instrumentDifficulties = {
  guitar: [
    "intervals",
    "one-string-melody",
    "simple-melody",
    "complex-melody",
    "easy-riffs",
    "hard-riffs",
    "key-of-g-diatonic-chords-easy",
    "key-of-g-diatonic-chords-hard",
    "key-of-g-diatonic-chords-with-extensions",
    "any-key-diatonic-chords-easy",
    "any-key-diatonic-chords-hard",
    "any-key-diatonic-chords-with-extensions",
    "no-restrictions",
  ],
  piano: [
    "intervals",
    "simple-melody",
    "complex-melody",
    "easy-riffs",
    "hard-riffs",
    "key-of-c-diatonic-chords-easy",
    "key-of-c-diatonic-chords-hard",
    "key-of-c-diatonic-chords-with-extensions",
    "any-key-diatonic-chords-easy",
    "any-key-diatonic-chords-hard",
    "any-key-diatonic-chords-with-extensions",
    "no-restrictions",
  ],
  bass: [
    "intervals",
    "one-string-melody",
    "simple-melody",
    "complex-melody",
    "easy-riffs",
    "hard-riffs",
    "key-of-g-diatonic-chords-easy",
    "key-of-g-diatonic-chords-hard",
    "key-of-g-diatonic-chords-with-extensions",
    "any-key-diatonic-chords-easy",
    "any-key-diatonic-chords-hard",
    "any-key-diatonic-chords-with-extensions",
    "no-restrictions",
  ],
  "guitar-bass": [
    "key-of-g-diatonic-chords-easy",
    "key-of-g-diatonic-chords-hard",
    "key-of-g-diatonic-chords-with-extensions",
    "any-key-diatonic-chords-easy",
    "any-key-diatonic-chords-hard",
    "any-key-diatonic-chords-with-extensions",
    "no-restrictions",
  ],
  "guitar-bass-piano": [
    "key-of-g-diatonic-chords-easy",
    "key-of-g-diatonic-chords-hard",
    "key-of-g-diatonic-chords-with-extensions",
    "any-key-diatonic-chords-easy",
    "any-key-diatonic-chords-hard",
    "any-key-diatonic-chords-with-extensions",
    "no-restrictions",
  ],
};

export const realSongListRealDifficultyFlatArray = [
  {
    audioTrackId: 1,
    userId: 1,
    songName: "El Paso",
    songTip: "el paso tip",
    songKey: "",
    songChords: "el paso chords",
    songInstrument: "guitar",
    songDifficulty: "simple-melody",
    songBlobUrl: "/Songs/ET_MO_A_ElPaso.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 2,
    userId: 1,
    songName: "GOTTV1",
    songTip: "gotv1 tip",
    songKey: "",
    songChords: "gotv1 chords",
    songInstrument: "guitar",
    songDifficulty: "simple-melody",
    songBlobUrl: "/Songs/ET_MO_I_GOTTV1.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 3,
    userId: 1,
    songName: "1415G",
    songTip: "Come on dude really?",
    songKey: "G",
    songChords: "1415G chords",
    songInstrument: "guitar",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_1415G.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 4,
    userId: 1,
    songName: "1465G",
    songTip: "Come on dude really?",
    songKey: "G",
    songChords: "1465G chords",
    songInstrument: "guitar",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_1465G.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 5,
    userId: 1,
    songName: "1524G",
    songTip: "Come on dude really?",
    songKey: "G",
    songChords: "1524G chords",
    songInstrument: "guitar",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_1524G.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 6,
    userId: 1,
    songName: "1645G",
    songTip: "Come on dude really?",
    songKey: "G",
    songChords: "1645G chords",
    songInstrument: "guitar",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_1645G.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 7,
    userId: 1,
    songName: "5411G",
    songTip: "Come on dude really?",
    songKey: "G",
    songChords: "5411G chords",
    songInstrument: "guitar",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_5411G.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 8,
    userId: 1,
    songName: "Blue Chorus",
    songTip: "Blue Chorus tip",
    songKey: "",
    songChords: "Blue Chorus chords",
    songInstrument: "guitar",
    songDifficulty: "any-key-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_Blue_Chorus.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 9,
    userId: 1,
    songName: "Simple Man",
    songTip: "Simple Man tip",
    songKey: "",
    songChords: "Simple Man chords",
    songInstrument: "guitar",
    songDifficulty: "any-key-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_Simple_Man.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 10,
    userId: 1,
    songName: "Hurt",
    songTip: "Hurt tip",
    songKey: "",
    songChords: "Hurt chords",
    songInstrument: "guitar",
    songDifficulty: "any-key-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_Guitar_Hurt.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 11,
    userId: 1,
    songName: "Cavalry",
    songTip: "Cavalry tip",
    songKey: "",
    songChords: "Cavalry chords",
    songInstrument: "guitar",
    songDifficulty: "no-restrictions",
    songBlobUrl: "/Songs/ET_Guitar_Cavalry.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 12,
    userId: 1,
    songName: "Nobody Knows You When You're Down And Out",
    songTip: "Nobody Knows You When You're Down And Out tip",
    songKey: "",
    songChords: "Nobody Knows You When You're Down And Out chords",
    songInstrument: "guitar",
    songDifficulty: "no-restrictions",
    songBlobUrl:
      "/Songs/ET_Guitar_Nobody_Knows_You_When_You're_Down_And_Out.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 13,
    userId: 1,
    songName: "Something",
    songTip: "Something tip",
    songKey: "",
    songChords: "Something chords",
    songInstrument: "guitar",
    songDifficulty: "no-restrictions",
    songBlobUrl: "/Songs/ET_Guitar_Something.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 14,
    userId: 1,
    songName: "G 15",
    songTip: "G 15 tip",
    songKey: "G",
    songChords: "G 15 chords  ",
    songInstrument: "bass",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_BO_B_G_15.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 15,
    userId: 1,
    songName: "G 1415",
    songTip: "G 1415 tip",
    songKey: "G",
    songChords: "G 1415 chords",
    songInstrument: "bass",
    songDifficulty: "key-of-g-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_BO_B_G_1415.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 16,
    userId: 1,
    songName: "A 1415",
    songTip: "A 1415 tip",
    songKey: "A",
    songChords: "A 1415 chords",
    songInstrument: "bass",
    songDifficulty: "any-key-diatonic-chords-easy",
    songBlobUrl: "/Songs/ET_BO_I_A_1415.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 17,
    userId: 1,
    songName: "12BB",
    songTip: "12BB tip",
    songKey: "",
    songChords: "12BB chords",
    songInstrument: "bass",
    songDifficulty: "any-key-diatonic-chords-hard",
    songBlobUrl: "/Songs/ET_BO_A_12BB.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    audioTrackId: 18,
    userId: 1,
    songName: "Fifth",
    songTip: "G",
    songKey: "",
    songChords: "1-5 G-D",
    songInstrument: "guitar",
    songDifficulty: "intervals",
    songBlobUrl: "/Songs/1-5GI.mp3",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
];

export const notes = [
  { display: "A", value: "A" },
  { display: "A#/Bb", value: "A#" },
  { display: "B", value: "B" },
  { display: "C", value: "C" },
  { display: "C#/Db", value: "C#" },
  { display: "D", value: "D" },
  { display: "D#/Eb", value: "D#" },
  { display: "E", value: "E" },
  { display: "F", value: "F" },
  { display: "F#/Gb", value: "F#" },
  { display: "G", value: "G" },
  { display: "G#/Ab", value: "G#" },
];

export const scales = {
  note: [0], // Just the root note
  major: [0, 2, 4, 5, 7, 9, 11],
  minor: [0, 2, 3, 5, 7, 8, 10],
  majorPentatonic: [0, 2, 4, 7, 9],
  minorPentatonic: [0, 3, 5, 7, 10],
  majorArpeggio: [0, 4, 7],
  minorArpeggio: [0, 3, 7],
};
export const notesss = [
  "A",
  "A#",
  "B",
  "C",
  "C#",
  "D",
  "D#",
  "E",
  "F",
  "F#",
  "G",
  "G#",
];

export const stringNames = ["E", "B", "G", "D", "A", "E"];
